import { blogPosts } from '@/lib/data'
import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>The Miseducation of Orlundo Hubbard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <h1>My Blog</h1>

       <div>
       {blogPosts.map((item) => (
         <div key={item.slug}>
          <div>
            <Link href={`/blog/${item.slug}`}>{item.title}</Link>
            </div>
          <div>{item.date.toString}</div>
          <div>{item.content}</div>
         </div>
       ))}
       </div>
      </main>
    </>
  )
}
